### ISSUE TITLE
make check testfiles do not match updated output

### ISSUE THREAD

**Issue by yimjay** [qingyi-yan/POET#36]
`make check` produces error for checks in directories `test/parseC`, `examples`, and `parsePy` (the latter documented in issue #26 ) 

`make check`, runs 2 commands for each input file:
`$(comp) out $(srcdir)/poet_$(input).out.save`, which compares the parsed AST against expected AST -> produces diff
`$(comp) poet_$(input).c $(srcdir)/poet_$(input).c.save`, which compares the parsed then unparsed input file against the expected result in `poet_$(input).c.save` -> OK

Diff files when testing: `test/parseC/jacobi7_4_opt.c`
[diff_jacobi.txt](https://github.com/qingyi-yan/POET/files/12602219/diff_jacobi.txt)
[diff_jacobi_b_moved.txt](https://github.com/qingyi-yan/POET/files/12602218/diff_jacobi_b_moved.txt) (after updating the order "B" is listed in symtab)

Diff files when testing: `test/parseC/tri.c`
[diff_tri.txt](https://github.com/qingyi-yan/POET/files/12602221/diff_tri.txt)
[diff_tri_typedef_replaced.txt](https://github.com/qingyi-yan/POET/files/12602220/diff_tri_typedef_replaced.txt) (replaced CODE.TypeDef with CODE.TypeDefParse)

Diff files when testing: `examples/tomcatv.C`
[poet_tomcatv.txt](https://github.com/qingyi-yan/POET/files/12602235/poet_tomcatv.txt)

**Comment by qingyi-yan** [comment]
Fixed by the newest commit.
