### ISSUE TITLE
analyze/automatically extract object-oriented abstraction

### ISSUE THREAD

**Issue by yimjay** [qingyi-yan/POET#7]

**Comment by qingyi-yan** [comment]
Here is my Google doc for refinement of the problem and initial design of solution strategies.

**Comment by qingyi-yan** [comment]
https://docs.google.com/document/d/1vSJGySOSzB9DnWKJK5j90B9pGOwnmWLrIip49iaVx8o/edit

**Comment by qingyi-yan** [comment]
The next thing to do is the identify 2-3 sequential C++ classes used in the paper http://www.cs.uccs.edu/~qyi/papers/ASE2019.pdf
Then we should try manually map the stack and queue specifications in the Google design doc to these C++ classes. 
Then we are going to use these input + output specifications and mappings as test cases to set up our working repository,.
Then I will design an algorithm to try automatically perform the needed analysis.
Let's set up the repository in Github as a separate project.

**Comment by qingyi-yan** [comment]
Once the new project repository is created, we should move this thread to the new repository.

**Comment by yimjay** [comment]
Issue copied to a separate repository (yimjay/code-extraction) after conversation with Dr. Yi so this version will be closed.
